# Generated by Django 4.2.7 on 2025-09-03 12:37

import apps.job_orders.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("job_orders", "0002_joborder_tracking_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManufacturingJobOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Stationary", "Stationary"),
                            ("Electronics", "Electronics"),
                            ("Food", "Food"),
                            ("BOPP", "BOPP"),
                            ("Printing", "Printing"),
                            ("Packaging", "Packaging"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "job_order",
                    models.CharField(
                        default=apps.job_orders.models.generate_job_order,
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "submission_id",
                    models.CharField(
                        blank=True,
                        default=apps.job_orders.models.generate_submission_id,
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("treatment", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "cutting_length",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("flap", models.CharField(blank=True, max_length=50, null=True)),
                ("printing", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "print_product",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("colors", models.CharField(blank=True, max_length=100, null=True)),
                ("order_info", models.TextField(blank=True, null=True)),
                ("size", models.CharField(blank=True, max_length=50, null=True)),
                ("micron", models.CharField(blank=True, max_length=50, null=True)),
                ("job_title", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="manufacturing_job_images/"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("quantity", models.CharField(blank=True, max_length=100, null=True)),
                ("order_quantity", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("estimated_delivery_date", models.DateField(blank=True, null=True)),
                ("actual_delivery_date", models.DateField(blank=True, null=True)),
                ("cycle_time", models.DurationField(blank=True, null=True)),
                ("production_status_date", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("in_production", "In Production"),
                            ("completed", "Completed"),
                            ("delivered", "Delivered"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("production_status", models.TextField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_manufacturing_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_manufacturing_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manufacturing_job_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_created"],
                "permissions": [
                    (
                        "can_approve_manufacturing_jobs",
                        "Can approve manufacturing job orders",
                    ),
                    (
                        "can_view_all_manufacturing_jobs",
                        "Can view all manufacturing job orders",
                    ),
                    (
                        "can_export_manufacturing_jobs",
                        "Can export manufacturing job orders",
                    ),
                    ("can_manage_production", "Can manage production status"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ManufacturingJobOrderComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="job_orders.manufacturingjoborder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
