# Generated by Django 4.2.7 on 2025-09-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="role_type",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("company_admin", "Company Admin"),
                    ("manager", "Manager"),
                    ("production_manager", "Production Manager"),
                    ("accountant", "Accountant"),
                    ("marketer", "Marketer"),
                    ("store_keeper", "Store Keeper"),
                    ("viewer", "Viewer"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
